// ทดสอบมิกเซอร์ (เสียงร้อง/ดนตรี/เปียโน) บนหน้าเว็บจริง (ต้องรัน backend :8000 + vite :5173)
import puppeteer from 'puppeteer-core'
let failed = 0
const check = (n, c, x = '') => { console.log(c ? 'PASS' : 'FAIL', n, x); if (!c) failed++ }
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new',
  args: ['--autoplay-policy=no-user-gesture-required', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'], defaultViewport: { width: 1600, height: 900 } })
const page = await browser.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto('http://localhost:5173', { waitUntil: 'networkidle0' })
await page.waitForSelector('[data-testid=statusbar] .dot.ok')
const pid = await page.evaluate(async () => (await fetch('http://localhost:8000/projects').then((r) => r.json())).filter((p) => p.analyzed && /song01/.test(p.title))[0].id)
await page.evaluate((id) => window.__melotab.getState().openProject(id), pid)
await page.waitForSelector('[data-testid=pianoroll] canvas')
await sleep(1500)
const TR = (fn) => page.evaluate(fn)
const set = (tid, v) => page.$eval(`[data-testid=${tid}]`, (el, v) => { const d = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value'); d.set.call(el, String(v)); el.dispatchEvent(new Event('input', { bubbles: true })) }, v)

check('ตอนแรกยังไม่เปิดมิกเซอร์ เล่นไฟล์เดียว', !(await TR(() => window.__getTransport().mixerOn)))
await page.click('[data-testid=mixer-toggle]')
await page.waitForSelector('[data-testid=vol-vocal]', { timeout: 60000 })
check('เปิดมิกเซอร์ได้ มีแถบเสียงร้อง/ดนตรี', await TR(() => window.__getTransport().mixerOn))
await page.click('[data-testid=play]')
await sleep(1200)
let n = await TR(() => window.__getTransport().srcs.length)
check('เล่นพร้อมกัน 2 stem (เสียงร้อง + ดนตรี)', n === 2, `${n} sources`)
await set('vol-vocal', 20); await set('vol-music', 80); await set('vol-piano', 150)
await sleep(200)
const g = await TR(() => { const t = window.__getTransport(); return { v: t.vocalGain.gain.value, m: t.instGain.gain.value, p: t.synthGain.gain.value, on: t.synthOn } })
check('ปรับระดับเสียงถึงโหนดเสียงจริง', Math.abs(g.v - 0.2) < 1e-6 && Math.abs(g.m - 0.8) < 1e-6 && Math.abs(g.p - 0.525) < 1e-6 && g.on, JSON.stringify(g))
const t1 = await TR(() => window.__getTransport().getTime()); await sleep(1000); const t2 = await TR(() => window.__getTransport().getTime())
check('เล่นต่อเนื่องปกติระหว่างปรับเสียง', t2 - t1 > 0.8 && t2 - t1 < 1.3, `${(t2 - t1).toFixed(2)} s`)
// ช้าลงในโหมดมิกเซอร์ (ยืดทั้ง 2 stem)
await page.select('[data-testid=rate]', '0.75')
await page.waitForFunction(() => !document.querySelector('[data-testid=rate]').disabled, { timeout: 120000 })
await sleep(500)
const info = await TR(() => { const t = window.__getTransport(); return { rate: t.rate, n: t.srcs.length, st: [...t.stretched.keys()] } })
check('ช้าลง 75% ใช้ stem ที่ยืดแล้วทั้ง 2 ตัว', info.rate === 0.75 && info.n === 2 && info.st.filter((k) => k.endsWith('@0.75')).length === 2, JSON.stringify(info))
await page.select('[data-testid=rate]', '1')
await sleep(500)
// พรีเซ็ต "เน้นเปียโน"
await set('vol-vocal', 100); await set('vol-music', 100); await set('vol-piano', 0)
await page.click('[data-testid=piano-focus]')
await sleep(300)
const v = await page.evaluate(() => [document.querySelector('[data-testid=vol-vocal]').value, document.querySelector('[data-testid=vol-music]').value, document.querySelector('[data-testid=vol-piano]').value])
check('ปุ่ม "เน้นเปียโน" = ร้อง 20 / ดนตรี 60 / เปียโน 150', v.join() === '20,60,150', v.join())
await page.screenshot({ path: '../../testdata/shots/50-mixer.png' })
await page.click('[data-testid=play]')
// ปิดมิกเซอร์กลับไปเล่นไฟล์เดียว
await page.click('[data-testid=mixer-toggle]')
await sleep(300)
check('ปิดมิกเซอร์แล้วกลับเป็นไฟล์เดียว', !(await TR(() => window.__getTransport().mixerOn)))
check('ไม่มี error', errors.length === 0, errors.join('|'))
await browser.close()
process.exit(failed ? 1 : 0)
